### ISSUE TITLE
GridRecyclerView problem

### ISSUE THREAD

**Issue by KadamMangesh** [antoniolg/MaterializeYourApp#13]
Hi I am using GridRecyclerView from your code. I am using this in relative layout. Problem I am facing is gridrecyclerview has internal scrolling. Is there any way by which this scrolling can be applied to whole screen?

**Comment by antoniolg** [comment]
You'll probably need to add the rest of the content as a row inside the `RecyclerView`. Google how to add a header to RecyclerView.
