### ISSUE TITLE
Downloaded and got a Trojan Malware warning

### ISSUE THREAD

**Issue by Shayne3000** [antoniolg/MaterializeYourApp#27]
I find this incredibly weird but I downloaded the zip file of the project, unpacked it and my AntiVirus software threw a trojan malware warning at me. Something to do with a CoinMiner. Worthy of note is the fact that I did nothing before this other than reviewing this project  so I doubt it could have come from the other sites I had open at the time i.e. StackOverflow or developer.android.com. Perhaps a quick safety check would be advisable.

**Comment by antoniolg** [comment]
This is raw code, and the zip is generated by Github, so difficult to see where a trojan could come from. As you can see, this repo hasn't been updated in the last 7 months.

**Comment by Shayne3000** [comment]
Understood. I'm just pointing out an extremely weird occurrence. Thanks for your correspondence.
