### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [antoniolg/MaterializeYourApp#3]
I've found this repo from here:
http://antonioleiva.com/navigation-view/
but when I try to import it, I get this error:
![untitled20150607221809](https://cloud.githubusercontent.com/assets/5357526/8025575/258d9e2a-0d63-11e5-8342-e6af0ad81bbf.png)
Why does it happen? and how do I fix it?

**Comment by KChernenko** [comment]
@AndroidDeveloperLB I've just deleted lines in the `build.gradle`:

```
signingConfigs {
        release {
            storeFile file(RELEASE_STORE_FILE)
            storePassword RELEASE_STORE_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
            keyPassword RELEASE_KEY_PASSWORD
        }
  }
```

And
`signingConfig signingConfigs.release`
In the `buildTypes` section.

**Comment by AndroidDeveloperLB** [comment]
I still have this issue. :(

**Comment by KChernenko** [comment]
@AndroidDeveloperLB try clean and rebuild project.

**Comment by KChernenko** [comment]
@AndroidDeveloperLB just have a look: https://gist.github.com/anonymous/c617a07c601009ae8270

**Comment by afflick** [comment]
Thanks @KChernenko !

**Comment by AndroidDeveloperLB** [comment]
@KChernenko What to look there for? I've used the normal import via Android-Studio, and it failed to import, so it won't even show the opened project.

**Comment by KChernenko** [comment]
@AndroidDeveloperLB after Android Studio shows you this error, you should press ok button, and find&fix `build.gradle` in the project hierarchy tree.

**Comment by AndroidDeveloperLB** [comment]
@KChernenko Pressing the OK dialog will close it and return to the previous screen I had (previously opened project, for example), so I can't choose the build.gradle file.
Do you mean I should edit the file outside of Android-Studio? This isn't needed for any repo. Why does it occur here?

**Comment by afflick** [comment]
@AndroidDeveloperLB if you are using the clone project from Github, it should already be downloaded. After you press OK, go to "open existing project" in the Android Studio start screen, you will have to navigate to the folder it saved the repo and open it again. Once you have it open you can apply the changes in the build.gradle file.

**Comment by AndroidDeveloperLB** [comment]
After double importing (which I don't understand why it's needed), I see the "build.gradle" quite minimal. It does lack some important things. It doesn't even have "buildTypes"...
How come?
How do I add the buildTypes that you wanted? In a normal app, I see both "defaultConfig" and "buildTypes" being set.
Why does the configuration of the project miss all those things?

**Comment by afflick** [comment]
@AndroidDeveloperLB There is several build.gradle files within the project, look through every folder in the tree and you will find the one with the defaultConfig and buildTypes in it (I'm not at my PC with Android Studio atm sorry). Once you have put the right values in it make sure you clean and rebuild the project.

**Comment by AndroidDeveloperLB** [comment]
Oh, for some reason this file is missing from the "gradle scripts" category. After deleting the problematic lines, all went well.
How could this be?
Also, may I ask something about the guidelines?
What should I do if I can't find anything to put on the title of the nav-drawer, and for the icons of the items?
