### ISSUE TITLE
What if I have a clickable view inside the nested scroll view

### ISSUE THREAD

**Issue by escobar5** [antoniolg/MaterializeYourApp#4]
Hi,

First of all, thanks for your sample, it was of great help for me.
I have a problem though, and I hope you can help me with it.

If I have the same layout you have in activity_detail.xml but I set the CardView as clickable="true", then I cannot scroll from within that view.

Do you know how to address this problem?

**Comment by yangpeiyong** [comment]
Have you solved this problem?

**Comment by antoniolg** [comment]
That looks like a bug in the design support library, have you tried latest version (23.0.0)? I'd like to update this repo asap, but running out of time these days, sorry.

**Comment by escobar5** [comment]
thanks @antoniolg , it definately seems like a bug, I cannot update to the latest version yet because I'm using Xamarin. for the moment I've just sorted it out like this: http://stackoverflow.com/questions/31320207/clickable-cardview-inside-nestedscroll-doesnt-trigger-scrolling

**Comment by shivasurya** [comment]
i too have same problem! any fixes ?

**Comment by antoniolg** [comment]
This looks like a matter of touch interaction, and not related to this example, so closing it.

**Comment by shivasurya** [comment]
Y closed ? Sir! May I know any fixes ?

**Comment by antoniolg** [comment]
Haven't tested, but this issue is not a problem in the example. Open a StackOverflow question if you need more help.
