### ISSUE TITLE
Non-scrollable detail activity in landscape mode

### ISSUE THREAD

**Issue by phishboh** [antoniolg/MaterializeYourApp#5]
Thanks a lot for this demo app, very informative.

On my phone, only the non-scrollable image is visible in the detail activity in landscape mode. This means that the card view is not visible and scrolling is not possible.

**Comment by antoniolg** [comment]
Yeah it's true, the app is not optimized for landscape layout, and it's indeed a problem that the image part is not scrollable. I'm not completely sure, but I think it's a library limitation that will be (hopefully) fixed at some moment.

**Comment by phishboh** [comment]
OK.
I started experimenting just a little with the image view. Should you have any input as to why no image is shown at all when changing from SquaredImageView to standard ImageView in the detail layout, you're welcome to share your ideas.

**Comment by antoniolg** [comment]
Tried by setting a fixed height? 200dp for instance.

**Comment by phishboh** [comment]
I got it working. Thanks.

**Comment by antoniolg** [comment]
This is not an issue anymore in latest versions of design support library. The header is also scrollable.
