### ISSUE TITLE
Multiple detail activities

### ISSUE THREAD

**Issue by phishboh** [antoniolg/MaterializeYourApp#6]
Fyi, multiple detail activities are started when (accidentally) double clicking a grid item. I assume it happens because of the 200 ms ripple effect delay. When clicking back twice to get back to the grid, the item image turns white.

**Comment by antoniolg** [comment]
Yeah, that's true thanks. It's not a production ready app anyway, just a showcase, so not very worried about the details. But I'll fix it if I find some time.
