### ISSUE TITLE
titlebar got blank after scroll down and up

### ISSUE THREAD

**Issue by nadeemkhan** [antoniolg/MaterializeYourApp#9]
![device-2015-09-14-125202](https://cloud.githubusercontent.com/assets/1510017/9844299/b564d1f2-5adf-11e5-875a-c9ff57230034.png)

**Comment by antoniolg** [comment]
Yeah, not sure if is an bug from the library or myself. Found this reported issue on design library that seems to be the same problem:

https://code.google.com/p/android/issues/detail?id=184528&thanks=184528&ts=1441110553

**Comment by nadeemkhan** [comment]
got it thanks for reply
